name: CI of sch-core-python

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]
        build-type: [Debug, RelWithDebInfo]
        exclude:
          # No Debug build in Windows
          - os: windows-latest
            build-type: Debug

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython cython3 python-nose python3-nose python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev libboost-all-dev
        macos: |
          brew: eigen boost
          pip: Cython coverage nose numpy
        windows: |
          pip: Cython coverage nose numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
        github: |
          - path: jrl-umi3218/Eigen3ToPython
          - path: jrl-umi3218/SpaceVecAlg
          - path: jrl-umi3218/sch-core
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        build-type: ${{ matrix.build-type }}
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [sch-core-python] Build *${{ matrix.os }}/${{ matrix.build-type }}* failed on ${{ github.ref }}
