name: CI of sch-core-python

on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        build-type: [Debug, RelWithDebInfo]
        exclude:
          # No Debug build in Windows
          - os: windows-latest
            build-type: Debug

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install pip for Python 2 (Ubuntu 20.04)
      run: |
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
        sudo python2 get-pip.py
        rm -f get-pip.py
      if: matrix.os == 'ubuntu-20.04'
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython cython3 python-pytest python3-pytest python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev libboost-all-dev
        macos: |
          brew: eigen boost
          pip: Cython coverage pytest numpy
        windows: |
          pip: Cython coverage pytest numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
        github: |
          - path: jrl-umi3218/Eigen3ToPython
          - path: jrl-umi3218/SpaceVecAlg
          - path: jrl-umi3218/sch-core
            options: -DCMAKE_CXX_STANDARD=11
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        build-type: ${{ matrix.build-type }}
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [sch-core-python] Build *${{ matrix.os }}/${{ matrix.build-type }}* failed on ${{ github.ref }}
